name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.22
      GOLANGCI_LINT_VERSION: v1.58.1
      YAEGI_VERSION: v0.9.0
      CGO_ENABLED: 0
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check Out The Repo
        uses: actions/checkout@v5.0.0
        with:
          path: go/src/github.com/${{ github.repository }}
          fetch-depth: 0


      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: go/src/github.com/${{ github.repository }}/go.mod
          cache: true
          cache-dependency-path: go.sum


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0

      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      - name: Setup GOPATH
        run: go env -w GOPATH=${{ github.workspace }}/go


      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          # git diff --exit-code go.sum
          go mod download
          go mod vendor
          # git diff --exit-code ./vendor/

      - name: Lint and Tests
        run: make

      - name: Run tests with Yaegi
        run: make yaegi_test
        env:
          GOPATH: ${{ github.workspace }}/go
